version: 2

project_name: telemetron

before:
  hooks:
    - go mod download

builds:
  - id: telemetron
    main: ./cmd/telemetron
    binary: telemetron
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ if .Version }}{{ .Version }}-snapshot{{ else }}0.0.0-snapshot{{ end }}"

changelog:
  use: git
  sort: asc
